name: Deploy to GitHub Pages
env:
  project_path: 'Financr'
on:
  push:
    branches: [ main ]  
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.102'
        include-prerelease: true

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Substitute base href
      run: sed -i 's/base href="\/"/base href="\/${{ github.event.repository.name }}\/"/' ${{ env.project_path }}/wwwroot/index.html
      shell: bash
    - name: Setup SPA 404 page redirection
      run: |
        cp ${{ github.action_path }}/404.html ${{ env.project_path }}/wwwroot
        cp ${{ github.action_path }}/redirect.js ${{ env.project_path }}/wwwroot
        sed -i '/blazor.webassembly.js/i \    <script src="redirect.js"><\/script>' ${{ env.project_path }}/wwwroot/index.html
      shell: bash
    - name: Publish application
      run: dotnet publish -c Release -o ${{ runner.temp }}/${{ github.action }}
      shell: bash
    - name: Create gh-pages branch
      run: |
        git checkout --orphan gh-pages
        git clean -fdx
        git rm -rf .
        cp -r ${{ runner.temp }}/${{ github.action }}/wwwroot/. .
        touch .nojekyll
      shell: bash
    - name: Commit and push
      run: |
        git add .
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -m 'Deploy application to GitHub Pages'
        git push -f -u origin gh-pages
      shell: bash